env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: eu-west-2
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_IMAGE_NAME: code-test-dev-image-698bba4
  ECR_REPO: 139227058951.dkr.ecr.eu-west-2.amazonaws.com
  LAMBDA_FUNCTION_ARN: arn:aws:lambda:eu-west-2:139227058951:function:code-test-dev-lambda-ad5312d
  LAMBDA_FUNCTION_LATEST_VERSION_ALIAS_NAME: code-test-dev-latest-alias-8976075
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          node-version-file: .nvmrc
      - run: bash ./scripts/setup.sh
      - run: npx lerna exec --stream --concurrency 1 --scope=backend -- bash
          scripts/ci/setup.sh
      - run: npx lerna exec --stream --concurrency 1 --scope=backend -- bash
          scripts/ci/deploy.sh
name: Deploy systems/backend
on:
  push:
    branches:
      - main
    paths:
      - systems/backend/**
