env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Wait for infrastructure deployment
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          allowed-conclusions: success,skipped
          check-name: infrastructure-deploy
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          node-version-file: .nvmrc
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ env.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - run: bash ./scripts/setup.sh
      - run: npx lerna exec --stream --concurrency 1 --scope=frontend -- bash
          scripts/ci/deploy.sh
name: Deploy systems/frontend
on:
  push:
    branches:
      - main
    paths:
      - systems/frontend/**
  workflow_dispatch:
